# Generated by Django 5.1.1 on 2024-10-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_employee_branchlocation_employee_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=50, verbose_name='phone number'),
        ),
    ]
