# Generated by Django 5.1.1 on 2024-10-19 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('persons', '0003_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assignedRoute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.route', verbose_name='Assigned Route'),
        ),
    ]
