# Generated by Django 5.1.1 on 2024-10-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='nameB',
        ),
    ]
